# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80d19edf3ebde523f78d8cafe702373ae7a3d93d38b4ad613051094e740679da28b8e78f5d03b866caf0a3a869a5d2009605987675d2f8877b752a223eba0428

test:
  secret_key_base: 5386439b951410aaa822069adbadd2e99dc3324a2ce0d9d566bff20303a6bf2413f7b4daa33cdc193b65a967c7b091c886a818bf045436ac00b2b78caf24673a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
